// Code generated by go-swagger; DO NOT EDIT.

package wallet

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/oxygenpay/oxygen/pkg/api-kms/v1/model"
)

// CreateSolanaTransactionReader is a Reader for the CreateSolanaTransaction structure.
type CreateSolanaTransactionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateSolanaTransactionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCreateSolanaTransactionCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateSolanaTransactionBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateSolanaTransactionCreated creates a CreateSolanaTransactionCreated with default headers values
func NewCreateSolanaTransactionCreated() *CreateSolanaTransactionCreated {
	return &CreateSolanaTransactionCreated{}
}

/*
	CreateSolanaTransactionCreated describes a response with status code 201, with default header values.

Transaction Created
*/
type CreateSolanaTransactionCreated struct {
	Payload *model.SolanaTransaction
}

func (o *CreateSolanaTransactionCreated) Error() string {
	return fmt.Sprintf("[POST /wallet/{walletId}/transaction/solana][%d] createSolanaTransactionCreated  %+v", 201, o.Payload)
}
func (o *CreateSolanaTransactionCreated) GetPayload() *model.SolanaTransaction {
	return o.Payload
}

func (o *CreateSolanaTransactionCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.SolanaTransaction)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateSolanaTransactionBadRequest creates a CreateSolanaTransactionBadRequest with default headers values
func NewCreateSolanaTransactionBadRequest() *CreateSolanaTransactionBadRequest {
	return &CreateSolanaTransactionBadRequest{}
}

/*
	CreateSolanaTransactionBadRequest describes a response with status code 400, with default header values.

Validation error / Not found
*/
type CreateSolanaTransactionBadRequest struct {
	Payload *model.ErrorResponse
}

func (o *CreateSolanaTransactionBadRequest) Error() string {
	return fmt.Sprintf("[POST /wallet/{walletId}/transaction/solana][%d] createSolanaTransactionBadRequest  %+v", 400, o.Payload)
}
func (o *CreateSolanaTransactionBadRequest) GetPayload() *model.ErrorResponse {
	return o.Payload
}

func (o *CreateSolanaTransactionBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
