// Code generated by go-swagger; DO NOT EDIT.

package wallet

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/oxygenpay/oxygen/pkg/api-kms/v1/model"
)

// NewCreateSolanaTransactionParams creates a new CreateSolanaTransactionParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateSolanaTransactionParams() *CreateSolanaTransactionParams {
	return &CreateSolanaTransactionParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateSolanaTransactionParamsWithTimeout creates a new CreateSolanaTransactionParams object
// with the ability to set a timeout on a request.
func NewCreateSolanaTransactionParamsWithTimeout(timeout time.Duration) *CreateSolanaTransactionParams {
	return &CreateSolanaTransactionParams{
		timeout: timeout,
	}
}

// NewCreateSolanaTransactionParamsWithContext creates a new CreateSolanaTransactionParams object
// with the ability to set a context for a request.
func NewCreateSolanaTransactionParamsWithContext(ctx context.Context) *CreateSolanaTransactionParams {
	return &CreateSolanaTransactionParams{
		Context: ctx,
	}
}

// NewCreateSolanaTransactionParamsWithHTTPClient creates a new CreateSolanaTransactionParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateSolanaTransactionParamsWithHTTPClient(client *http.Client) *CreateSolanaTransactionParams {
	return &CreateSolanaTransactionParams{
		HTTPClient: client,
	}
}

/*
CreateSolanaTransactionParams contains all the parameters to send to the API endpoint

	for the create solana transaction operation.

	Typically these are written to a http.Request.
*/
type CreateSolanaTransactionParams struct {

	// Data.
	Data *model.CreateSolanaTransactionRequest

	/* WalletID.

	   Wallet UUID
	*/
	WalletID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create solana transaction params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateSolanaTransactionParams) WithDefaults() *CreateSolanaTransactionParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create solana transaction params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateSolanaTransactionParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create solana transaction params
func (o *CreateSolanaTransactionParams) WithTimeout(timeout time.Duration) *CreateSolanaTransactionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create solana transaction params
func (o *CreateSolanaTransactionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create solana transaction params
func (o *CreateSolanaTransactionParams) WithContext(ctx context.Context) *CreateSolanaTransactionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create solana transaction params
func (o *CreateSolanaTransactionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create solana transaction params
func (o *CreateSolanaTransactionParams) WithHTTPClient(client *http.Client) *CreateSolanaTransactionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create solana transaction params
func (o *CreateSolanaTransactionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the create solana transaction params
func (o *CreateSolanaTransactionParams) WithData(data *model.CreateSolanaTransactionRequest) *CreateSolanaTransactionParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the create solana transaction params
func (o *CreateSolanaTransactionParams) SetData(data *model.CreateSolanaTransactionRequest) {
	o.Data = data
}

// WithWalletID adds the walletID to the create solana transaction params
func (o *CreateSolanaTransactionParams) WithWalletID(walletID string) *CreateSolanaTransactionParams {
	o.SetWalletID(walletID)
	return o
}

// SetWalletID adds the walletId to the create solana transaction params
func (o *CreateSolanaTransactionParams) SetWalletID(walletID string) {
	o.WalletID = walletID
}

// WriteToRequest writes these params to a swagger request
func (o *CreateSolanaTransactionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Data != nil {
		if err := r.SetBodyParam(o.Data); err != nil {
			return err
		}
	}

	// path param walletId
	if err := r.SetPathParam("walletId", o.WalletID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
