// Code generated by go-swagger; DO NOT EDIT.

package wallet

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/cryptolink/cryptolink/pkg/api-kms/v1/model"
)

// CreateMoneroTransactionReader is a Reader for the CreateMoneroTransaction structure.
type CreateMoneroTransactionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateMoneroTransactionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCreateMoneroTransactionCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateMoneroTransactionBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateMoneroTransactionCreated creates a CreateMoneroTransactionCreated with default headers values
func NewCreateMoneroTransactionCreated() *CreateMoneroTransactionCreated {
	return &CreateMoneroTransactionCreated{}
}

/*
	CreateMoneroTransactionCreated describes a response with status code 201, with default header values.

Transaction Created
*/
type CreateMoneroTransactionCreated struct {
	Payload *model.MoneroTransaction
}

func (o *CreateMoneroTransactionCreated) Error() string {
	return fmt.Sprintf("[POST /wallet/{walletId}/transaction/monero][%d] createMoneroTransactionCreated  %+v", 201, o.Payload)
}
func (o *CreateMoneroTransactionCreated) GetPayload() *model.MoneroTransaction {
	return o.Payload
}

func (o *CreateMoneroTransactionCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.MoneroTransaction)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateMoneroTransactionBadRequest creates a CreateMoneroTransactionBadRequest with default headers values
func NewCreateMoneroTransactionBadRequest() *CreateMoneroTransactionBadRequest {
	return &CreateMoneroTransactionBadRequest{}
}

/*
	CreateMoneroTransactionBadRequest describes a response with status code 400, with default header values.

Validation error / Not found
*/
type CreateMoneroTransactionBadRequest struct {
	Payload *model.ErrorResponse
}

func (o *CreateMoneroTransactionBadRequest) Error() string {
	return fmt.Sprintf("[POST /wallet/{walletId}/transaction/monero][%d] createMoneroTransactionBadRequest  %+v", 400, o.Payload)
}
func (o *CreateMoneroTransactionBadRequest) GetPayload() *model.ErrorResponse {
	return o.Payload
}

func (o *CreateMoneroTransactionBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
