// Code generated by go-swagger; DO NOT EDIT.

package wallet

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/oxygenpay/oxygen/pkg/api-kms/v1/model"
)

// NewCreateMoneroTransactionParams creates a new CreateMoneroTransactionParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateMoneroTransactionParams() *CreateMoneroTransactionParams {
	return &CreateMoneroTransactionParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateMoneroTransactionParamsWithTimeout creates a new CreateMoneroTransactionParams object
// with the ability to set a timeout on a request.
func NewCreateMoneroTransactionParamsWithTimeout(timeout time.Duration) *CreateMoneroTransactionParams {
	return &CreateMoneroTransactionParams{
		timeout: timeout,
	}
}

// NewCreateMoneroTransactionParamsWithContext creates a new CreateMoneroTransactionParams object
// with the ability to set a context for a request.
func NewCreateMoneroTransactionParamsWithContext(ctx context.Context) *CreateMoneroTransactionParams {
	return &CreateMoneroTransactionParams{
		Context: ctx,
	}
}

// NewCreateMoneroTransactionParamsWithHTTPClient creates a new CreateMoneroTransactionParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateMoneroTransactionParamsWithHTTPClient(client *http.Client) *CreateMoneroTransactionParams {
	return &CreateMoneroTransactionParams{
		HTTPClient: client,
	}
}

/*
CreateMoneroTransactionParams contains all the parameters to send to the API endpoint

	for the create monero transaction operation.

	Typically these are written to a http.Request.
*/
type CreateMoneroTransactionParams struct {

	// Data.
	Data *model.CreateMoneroTransactionRequest

	/* WalletID.

	   Wallet UUID
	*/
	WalletID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create monero transaction params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateMoneroTransactionParams) WithDefaults() *CreateMoneroTransactionParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create monero transaction params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateMoneroTransactionParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create monero transaction params
func (o *CreateMoneroTransactionParams) WithTimeout(timeout time.Duration) *CreateMoneroTransactionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create monero transaction params
func (o *CreateMoneroTransactionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create monero transaction params
func (o *CreateMoneroTransactionParams) WithContext(ctx context.Context) *CreateMoneroTransactionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create monero transaction params
func (o *CreateMoneroTransactionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create monero transaction params
func (o *CreateMoneroTransactionParams) WithHTTPClient(client *http.Client) *CreateMoneroTransactionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create monero transaction params
func (o *CreateMoneroTransactionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the create monero transaction params
func (o *CreateMoneroTransactionParams) WithData(data *model.CreateMoneroTransactionRequest) *CreateMoneroTransactionParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the create monero transaction params
func (o *CreateMoneroTransactionParams) SetData(data *model.CreateMoneroTransactionRequest) {
	o.Data = data
}

// WithWalletID adds the walletID to the create monero transaction params
func (o *CreateMoneroTransactionParams) WithWalletID(walletID string) *CreateMoneroTransactionParams {
	o.SetWalletID(walletID)
	return o
}

// SetWalletID adds the walletId to the create monero transaction params
func (o *CreateMoneroTransactionParams) SetWalletID(walletID string) {
	o.WalletID = walletID
}

// WriteToRequest writes these params to a swagger request
func (o *CreateMoneroTransactionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Data != nil {
		if err := r.SetBodyParam(o.Data); err != nil {
			return err
		}
	}

	// path param walletId
	if err := r.SetPathParam("walletId", o.WalletID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
