// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: merchant_subscriptions.sql

package repository

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const cancelMerchantSubscription = `-- name: CancelMerchantSubscription :exec
UPDATE merchant_subscriptions
SET
    auto_renew = false,
    cancelled_at = NOW(),
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) CancelMerchantSubscription(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, cancelMerchantSubscription, id)
	return err
}

const createMerchantSubscription = `-- name: CreateMerchantSubscription :one
INSERT INTO merchant_subscriptions (
    uuid,
    merchant_id,
    plan_id,
    status,
    current_period_start,
    current_period_end,
    payment_id,
    auto_renew,
    created_at,
    updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, uuid, merchant_id, plan_id, status, current_period_start, current_period_end, payment_id, auto_renew, created_at, updated_at, cancelled_at
`

type CreateMerchantSubscriptionParams struct {
	Uuid               uuid.UUID
	MerchantID         int64
	PlanID             string
	Status             string
	CurrentPeriodStart time.Time
	CurrentPeriodEnd   time.Time
	PaymentID          sql.NullInt64
	AutoRenew          sql.NullBool
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

func (q *Queries) CreateMerchantSubscription(ctx context.Context, arg CreateMerchantSubscriptionParams) (MerchantSubscription, error) {
	row := q.db.QueryRow(ctx, createMerchantSubscription,
		arg.Uuid,
		arg.MerchantID,
		arg.PlanID,
		arg.Status,
		arg.CurrentPeriodStart,
		arg.CurrentPeriodEnd,
		arg.PaymentID,
		arg.AutoRenew,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i MerchantSubscription
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.MerchantID,
		&i.PlanID,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.PaymentID,
		&i.AutoRenew,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CancelledAt,
	)
	return i, err
}

const getActiveSubscriptionByMerchantID = `-- name: GetActiveSubscriptionByMerchantID :one
SELECT id, uuid, merchant_id, plan_id, status, current_period_start, current_period_end, payment_id, auto_renew, created_at, updated_at, cancelled_at FROM merchant_subscriptions
WHERE merchant_id = $1
AND status IN ('active', 'pending_payment')
ORDER BY id DESC
LIMIT 1
`

func (q *Queries) GetActiveSubscriptionByMerchantID(ctx context.Context, merchantID int64) (MerchantSubscription, error) {
	row := q.db.QueryRow(ctx, getActiveSubscriptionByMerchantID, merchantID)
	var i MerchantSubscription
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.MerchantID,
		&i.PlanID,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.PaymentID,
		&i.AutoRenew,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CancelledAt,
	)
	return i, err
}

const getMerchantSubscriptionByID = `-- name: GetMerchantSubscriptionByID :one
SELECT id, uuid, merchant_id, plan_id, status, current_period_start, current_period_end, payment_id, auto_renew, created_at, updated_at, cancelled_at FROM merchant_subscriptions
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetMerchantSubscriptionByID(ctx context.Context, id int64) (MerchantSubscription, error) {
	row := q.db.QueryRow(ctx, getMerchantSubscriptionByID, id)
	var i MerchantSubscription
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.MerchantID,
		&i.PlanID,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.PaymentID,
		&i.AutoRenew,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CancelledAt,
	)
	return i, err
}

const getMerchantSubscriptionByUUID = `-- name: GetMerchantSubscriptionByUUID :one
SELECT id, uuid, merchant_id, plan_id, status, current_period_start, current_period_end, payment_id, auto_renew, created_at, updated_at, cancelled_at FROM merchant_subscriptions
WHERE uuid = $1
LIMIT 1
`

func (q *Queries) GetMerchantSubscriptionByUUID(ctx context.Context, argUuid uuid.UUID) (MerchantSubscription, error) {
	row := q.db.QueryRow(ctx, getMerchantSubscriptionByUUID, argUuid)
	var i MerchantSubscription
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.MerchantID,
		&i.PlanID,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.PaymentID,
		&i.AutoRenew,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CancelledAt,
	)
	return i, err
}

const linkPaymentToSubscription = `-- name: LinkPaymentToSubscription :exec
UPDATE merchant_subscriptions
SET
    payment_id = $2,
    updated_at = NOW()
WHERE id = $1
`

type LinkPaymentToSubscriptionParams struct {
	ID        int64
	PaymentID sql.NullInt64
}

func (q *Queries) LinkPaymentToSubscription(ctx context.Context, arg LinkPaymentToSubscriptionParams) error {
	_, err := q.db.Exec(ctx, linkPaymentToSubscription, arg.ID, arg.PaymentID)
	return err
}

const listExpiringSubscriptions = `-- name: ListExpiringSubscriptions :many
SELECT id, uuid, merchant_id, plan_id, status, current_period_start, current_period_end, payment_id, auto_renew, created_at, updated_at, cancelled_at FROM merchant_subscriptions
WHERE status = 'active'
AND current_period_end <= $1
AND auto_renew = true
ORDER BY current_period_end ASC
`

func (q *Queries) ListExpiringSubscriptions(ctx context.Context, currentPeriodEnd time.Time) ([]MerchantSubscription, error) {
	rows, err := q.db.Query(ctx, listExpiringSubscriptions, currentPeriodEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MerchantSubscription
	for rows.Next() {
		var i MerchantSubscription
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.MerchantID,
			&i.PlanID,
			&i.Status,
			&i.CurrentPeriodStart,
			&i.CurrentPeriodEnd,
			&i.PaymentID,
			&i.AutoRenew,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CancelledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMerchantSubscriptionsByMerchantID = `-- name: ListMerchantSubscriptionsByMerchantID :many
SELECT id, uuid, merchant_id, plan_id, status, current_period_start, current_period_end, payment_id, auto_renew, created_at, updated_at, cancelled_at FROM merchant_subscriptions
WHERE merchant_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListMerchantSubscriptionsByMerchantID(ctx context.Context, merchantID int64) ([]MerchantSubscription, error) {
	rows, err := q.db.Query(ctx, listMerchantSubscriptionsByMerchantID, merchantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MerchantSubscription
	for rows.Next() {
		var i MerchantSubscription
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.MerchantID,
			&i.PlanID,
			&i.Status,
			&i.CurrentPeriodStart,
			&i.CurrentPeriodEnd,
			&i.PaymentID,
			&i.AutoRenew,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CancelledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSubscriptionExpired = `-- name: MarkSubscriptionExpired :exec
UPDATE merchant_subscriptions
SET
    status = 'expired',
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkSubscriptionExpired(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markSubscriptionExpired, id)
	return err
}

const updateMerchantSubscription = `-- name: UpdateMerchantSubscription :one
UPDATE merchant_subscriptions
SET
    status = $2,
    current_period_start = $3,
    current_period_end = $4,
    payment_id = $5,
    auto_renew = $6,
    updated_at = $7
WHERE id = $1
RETURNING id, uuid, merchant_id, plan_id, status, current_period_start, current_period_end, payment_id, auto_renew, created_at, updated_at, cancelled_at
`

type UpdateMerchantSubscriptionParams struct {
	ID                 int64
	Status             string
	CurrentPeriodStart time.Time
	CurrentPeriodEnd   time.Time
	PaymentID          sql.NullInt64
	AutoRenew          sql.NullBool
	UpdatedAt          time.Time
}

func (q *Queries) UpdateMerchantSubscription(ctx context.Context, arg UpdateMerchantSubscriptionParams) (MerchantSubscription, error) {
	row := q.db.QueryRow(ctx, updateMerchantSubscription,
		arg.ID,
		arg.Status,
		arg.CurrentPeriodStart,
		arg.CurrentPeriodEnd,
		arg.PaymentID,
		arg.AutoRenew,
		arg.UpdatedAt,
	)
	var i MerchantSubscription
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.MerchantID,
		&i.PlanID,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.PaymentID,
		&i.AutoRenew,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CancelledAt,
	)
	return i, err
}
