// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Querier interface {
	AdvisoryTxLock(ctx context.Context, pgAdvisoryXactLock int64) error
	CalculateCustomerPayments(ctx context.Context, arg CalculateCustomerPaymentsParams) (int64, error)
	CancelMerchantSubscription(ctx context.Context, id int64) error
	CancelTransaction(ctx context.Context, arg CancelTransactionParams) error
	CheckSystemWalletExistsByAddress(ctx context.Context, address string) (Wallet, error)
	CountUnusedAddresses(ctx context.Context, xpubWalletID int64) (int64, error)
	CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (ApiToken, error)
	CreateBalance(ctx context.Context, arg CreateBalanceParams) (Balance, error)
	CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error)
	CreateDerivedAddress(ctx context.Context, arg CreateDerivedAddressParams) (DerivedAddress, error)
	CreateJobLog(ctx context.Context, arg CreateJobLogParams) error
	CreateMerchant(ctx context.Context, arg CreateMerchantParams) (Merchant, error)
	CreateMerchantAddress(ctx context.Context, arg CreateMerchantAddressParams) (MerchantAddress, error)
	CreateMerchantSubscription(ctx context.Context, arg CreateMerchantSubscriptionParams) (MerchantSubscription, error)
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error)
	CreatePaymentLink(ctx context.Context, arg CreatePaymentLinkParams) (PaymentLink, error)
	CreateRegistryItem(ctx context.Context, arg CreateRegistryItemParams) (Registry, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	CreateUsageTracking(ctx context.Context, arg CreateUsageTrackingParams) (UsageTracking, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateWallet(ctx context.Context, arg CreateWalletParams) (Wallet, error)
	CreateWalletLock(ctx context.Context, arg CreateWalletLockParams) (WalletLock, error)
	CreateXpubWallet(ctx context.Context, arg CreateXpubWalletParams) (XpubWallet, error)
	DeactivateXpubWallet(ctx context.Context, arg DeactivateXpubWalletParams) error
	DeleteAPITokenByID(ctx context.Context, id int64) error
	DeleteAPITokenByToken(ctx context.Context, token string) error
	DeleteMerchantAddress(ctx context.Context, arg DeleteMerchantAddressParams) error
	DeletePaymentLinkByPublicID(ctx context.Context, arg DeletePaymentLinkByPublicIDParams) error
	DeleteUser(ctx context.Context, id int64) error
	EagerLoadTransactionsByPaymentID(ctx context.Context, arg EagerLoadTransactionsByPaymentIDParams) ([]Transaction, error)
	GetAPIToken(ctx context.Context, arg GetAPITokenParams) (ApiToken, error)
	GetAPITokenByUUID(ctx context.Context, argUuid uuid.UUID) (ApiToken, error)
	GetActiveSubscriptionByMerchantID(ctx context.Context, merchantID int64) (MerchantSubscription, error)
	GetAvailableWallet(ctx context.Context, arg GetAvailableWalletParams) (Wallet, error)
	GetBalanceByFilter(ctx context.Context, arg GetBalanceByFilterParams) (Balance, error)
	GetBalanceByFilterWithLock(ctx context.Context, arg GetBalanceByFilterWithLockParams) (Balance, error)
	GetBalanceByID(ctx context.Context, arg GetBalanceByIDParams) (Balance, error)
	GetBalanceByIDWithLock(ctx context.Context, id int64) (Balance, error)
	GetBalanceByUUID(ctx context.Context, arg GetBalanceByUUIDParams) (Balance, error)
	GetBatchCustomers(ctx context.Context, arg GetBatchCustomersParams) ([]Customer, error)
	GetBatchExpiredPayments(ctx context.Context, arg GetBatchExpiredPaymentsParams) ([]Payment, error)
	GetCurrentPeriodUsage(ctx context.Context, arg GetCurrentPeriodUsageParams) (UsageTracking, error)
	GetCustomerByEmail(ctx context.Context, arg GetCustomerByEmailParams) (Customer, error)
	GetCustomerByID(ctx context.Context, arg GetCustomerByIDParams) (Customer, error)
	GetCustomerByUUID(ctx context.Context, arg GetCustomerByUUIDParams) (Customer, error)
	GetDerivedAddressByAddress(ctx context.Context, arg GetDerivedAddressByAddressParams) (DerivedAddress, error)
	GetDerivedAddressByID(ctx context.Context, id int64) (DerivedAddress, error)
	GetDerivedAddressByUUID(ctx context.Context, argUuid uuid.UUID) (DerivedAddress, error)
	GetLastDerivedIndex(ctx context.Context, xpubWalletID int64) (interface{}, error)
	GetLatestTransactionByPaymentID(ctx context.Context, entityID sql.NullInt64) (Transaction, error)
	GetMerchantAddressByAddress(ctx context.Context, arg GetMerchantAddressByAddressParams) (MerchantAddress, error)
	GetMerchantAddressByID(ctx context.Context, arg GetMerchantAddressByIDParams) (MerchantAddress, error)
	GetMerchantAddressByUUID(ctx context.Context, arg GetMerchantAddressByUUIDParams) (MerchantAddress, error)
	GetMerchantByID(ctx context.Context, arg GetMerchantByIDParams) (Merchant, error)
	GetMerchantByUUID(ctx context.Context, arg GetMerchantByUUIDParams) (Merchant, error)
	GetMerchantByUUIDAndCreatorID(ctx context.Context, arg GetMerchantByUUIDAndCreatorIDParams) (Merchant, error)
	GetMerchantSubscriptionByID(ctx context.Context, id int64) (MerchantSubscription, error)
	GetMerchantSubscriptionByUUID(ctx context.Context, argUuid uuid.UUID) (MerchantSubscription, error)
	GetNextUnusedAddress(ctx context.Context, xpubWalletID int64) (DerivedAddress, error)
	GetPaymentByID(ctx context.Context, arg GetPaymentByIDParams) (Payment, error)
	GetPaymentByMerchantIDAndOrderUUID(ctx context.Context, arg GetPaymentByMerchantIDAndOrderUUIDParams) (Payment, error)
	GetPaymentByMerchantIDs(ctx context.Context, arg GetPaymentByMerchantIDsParams) (Payment, error)
	GetPaymentByPublicID(ctx context.Context, publicID uuid.UUID) (Payment, error)
	GetPaymentLinkByID(ctx context.Context, arg GetPaymentLinkByIDParams) (PaymentLink, error)
	GetPaymentLinkByPublicID(ctx context.Context, arg GetPaymentLinkByPublicIDParams) (PaymentLink, error)
	GetPaymentLinkBySlug(ctx context.Context, slug string) (PaymentLink, error)
	GetPaymentsByType(ctx context.Context, arg GetPaymentsByTypeParams) ([]Payment, error)
	GetRecentCustomerPayments(ctx context.Context, arg GetRecentCustomerPaymentsParams) ([]Payment, error)
	GetRegistryItemByKey(ctx context.Context, arg GetRegistryItemByKeyParams) (Registry, error)
	GetSubscriptionPlanByID(ctx context.Context, id string) (SubscriptionPlan, error)
	GetSuperAdmins(ctx context.Context) ([]User, error)
	GetTransactionByHashAndNetworkID(ctx context.Context, arg GetTransactionByHashAndNetworkIDParams) (Transaction, error)
	GetTransactionByID(ctx context.Context, arg GetTransactionByIDParams) (Transaction, error)
	GetTransactionsByFilter(ctx context.Context, arg GetTransactionsByFilterParams) ([]Transaction, error)
	GetUsageTrackingByID(ctx context.Context, id int64) (UsageTracking, error)
	GetUsageTrackingByMerchantAndPeriod(ctx context.Context, arg GetUsageTrackingByMerchantAndPeriodParams) (UsageTracking, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByGoogleID(ctx context.Context, googleID sql.NullString) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	GetWalletByID(ctx context.Context, id int64) (Wallet, error)
	GetWalletByUUID(ctx context.Context, argUuid uuid.UUID) (Wallet, error)
	GetWalletForUpdateByID(ctx context.Context, id int64) (Wallet, error)
	GetWalletLock(ctx context.Context, arg GetWalletLockParams) (WalletLock, error)
	GetXpubWalletByID(ctx context.Context, id int64) (XpubWallet, error)
	GetXpubWalletByMerchantAndBlockchain(ctx context.Context, arg GetXpubWalletByMerchantAndBlockchainParams) (XpubWallet, error)
	GetXpubWalletByUUID(ctx context.Context, argUuid uuid.UUID) (XpubWallet, error)
	IncrementAPIUsage(ctx context.Context, arg IncrementAPIUsageParams) error
	IncrementPaymentUsage(ctx context.Context, arg IncrementPaymentUsageParams) error
	InsertBalanceAuditLog(ctx context.Context, arg InsertBalanceAuditLogParams) error
	LinkPaymentToSubscription(ctx context.Context, arg LinkPaymentToSubscriptionParams) error
	ListAPITokensByEntity(ctx context.Context, arg ListAPITokensByEntityParams) ([]ApiToken, error)
	ListAllBalancesByType(ctx context.Context, arg ListAllBalancesByTypeParams) ([]Balance, error)
	ListAllSubscriptionPlans(ctx context.Context) ([]SubscriptionPlan, error)
	ListBalances(ctx context.Context, arg ListBalancesParams) ([]Balance, error)
	ListDerivedAddressesByMerchantID(ctx context.Context, merchantID int64) ([]DerivedAddress, error)
	ListDerivedAddressesByWalletID(ctx context.Context, xpubWalletID int64) ([]DerivedAddress, error)
	ListExpiringSubscriptions(ctx context.Context, currentPeriodEnd time.Time) ([]MerchantSubscription, error)
	ListJobLogsByID(ctx context.Context, arg ListJobLogsByIDParams) ([]JobLog, error)
	ListMerchantAddresses(ctx context.Context, merchantID int64) ([]MerchantAddress, error)
	ListMerchantSubscriptionsByMerchantID(ctx context.Context, merchantID int64) ([]MerchantSubscription, error)
	ListMerchantsByCreatorID(ctx context.Context, arg ListMerchantsByCreatorIDParams) ([]Merchant, error)
	ListPaymentLinks(ctx context.Context, arg ListPaymentLinksParams) ([]PaymentLink, error)
	ListSubscriptionPlans(ctx context.Context) ([]SubscriptionPlan, error)
	ListUsageTrackingByMerchantID(ctx context.Context, arg ListUsageTrackingByMerchantIDParams) ([]UsageTracking, error)
	ListUsers(ctx context.Context) ([]User, error)
	ListXpubWalletsByMerchantID(ctx context.Context, merchantID int64) ([]XpubWallet, error)
	MarkAddressAsUsed(ctx context.Context, arg MarkAddressAsUsedParams) (DerivedAddress, error)
	MarkSubscriptionExpired(ctx context.Context, id int64) error
	MarkUserAsSuperAdmin(ctx context.Context, id int64) error
	PaginateCustomersAsc(ctx context.Context, arg PaginateCustomersAscParams) ([]Customer, error)
	PaginateCustomersDesc(ctx context.Context, arg PaginateCustomersDescParams) ([]Customer, error)
	PaginatePaymentsAsc(ctx context.Context, arg PaginatePaymentsAscParams) ([]Payment, error)
	PaginatePaymentsDesc(ctx context.Context, arg PaginatePaymentsDescParams) ([]Payment, error)
	PaginateWalletsByID(ctx context.Context, arg PaginateWalletsByIDParams) ([]Wallet, error)
	ReleaseWalletLock(ctx context.Context, id int64) error
	SetTransactionHash(ctx context.Context, arg SetTransactionHashParams) error
	SoftDeleteMerchantByUUID(ctx context.Context, argUuid uuid.UUID) error
	UpdateBalanceByID(ctx context.Context, arg UpdateBalanceByIDParams) (Balance, error)
	UpdateDerivedAddressTatumSubscription(ctx context.Context, arg UpdateDerivedAddressTatumSubscriptionParams) (DerivedAddress, error)
	UpdateMerchant(ctx context.Context, arg UpdateMerchantParams) (Merchant, error)
	UpdateMerchantAddress(ctx context.Context, arg UpdateMerchantAddressParams) (MerchantAddress, error)
	UpdateMerchantSettings(ctx context.Context, arg UpdateMerchantSettingsParams) error
	UpdateMerchantSubscription(ctx context.Context, arg UpdateMerchantSubscriptionParams) (MerchantSubscription, error)
	UpdatePayment(ctx context.Context, arg UpdatePaymentParams) (Payment, error)
	UpdatePaymentCustomerID(ctx context.Context, arg UpdatePaymentCustomerIDParams) error
	UpdatePaymentWebhookInfo(ctx context.Context, arg UpdatePaymentWebhookInfoParams) error
	UpdateRegistryItem(ctx context.Context, arg UpdateRegistryItemParams) (Registry, error)
	UpdateSubscriptionPlan(ctx context.Context, arg UpdateSubscriptionPlanParams) error
	UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error)
	UpdateUsageTracking(ctx context.Context, arg UpdateUsageTrackingParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error)
	UpdateWalletMainnetTransactionCounters(ctx context.Context, arg UpdateWalletMainnetTransactionCountersParams) error
	UpdateWalletTatumFields(ctx context.Context, arg UpdateWalletTatumFieldsParams) (Wallet, error)
	UpdateWalletTestnetTransactionCounters(ctx context.Context, arg UpdateWalletTestnetTransactionCountersParams) error
	UpdateXpubWalletLastIndex(ctx context.Context, arg UpdateXpubWalletLastIndexParams) (XpubWallet, error)
	UpdateXpubWalletTatumSubscription(ctx context.Context, arg UpdateXpubWalletTatumSubscriptionParams) (XpubWallet, error)
}

var _ Querier = (*Queries)(nil)
