// Hand-written repository methods for transaction_fills.
// NOT generated by sqlc — keep this file out of `sqlc generate`'s blast radius.
// Each on-chain transfer that contributes to an underpaid invoice is recorded
// here. Idempotent on (transaction_id, network_id, transaction_hash, vout_or_logidx).
package repository

import (
	"context"
	"database/sql"
	"time"

	"github.com/jackc/pgtype"
)

type TransactionFill struct {
	ID              int64
	TransactionID   int64
	NetworkID       string
	TransactionHash string
	VoutOrLogIdx    int32
	Amount          pgtype.Numeric
	SenderAddress   sql.NullString
	BlockNumber     sql.NullInt64
	Confirmations   int32
	Status          string
	ObservedAt      time.Time
	ConfirmedAt     sql.NullTime
}

const insertTransactionFill = `
INSERT INTO transaction_fills (
    transaction_id, network_id, transaction_hash, vout_or_logidx,
    amount, sender_address, block_number, confirmations, status, observed_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (transaction_id, network_id, transaction_hash, vout_or_logidx)
DO UPDATE SET
    confirmations = GREATEST(transaction_fills.confirmations, EXCLUDED.confirmations),
    status = CASE
        WHEN EXCLUDED.confirmations >= transaction_fills.confirmations
             AND EXCLUDED.status = 'confirmed' THEN 'confirmed'
        ELSE transaction_fills.status
    END,
    confirmed_at = CASE
        WHEN transaction_fills.confirmed_at IS NULL AND EXCLUDED.status = 'confirmed' THEN now()
        ELSE transaction_fills.confirmed_at
    END
RETURNING id, transaction_id, network_id, transaction_hash, vout_or_logidx,
          amount, sender_address, block_number, confirmations, status, observed_at, confirmed_at
`

type InsertTransactionFillParams struct {
	TransactionID   int64
	NetworkID       string
	TransactionHash string
	VoutOrLogIdx    int32
	Amount          pgtype.Numeric
	SenderAddress   sql.NullString
	BlockNumber     sql.NullInt64
	Confirmations   int32
	Status          string
	ObservedAt      time.Time
}

func (q *Queries) InsertTransactionFill(ctx context.Context, arg InsertTransactionFillParams) (TransactionFill, error) {
	row := q.db.QueryRow(ctx, insertTransactionFill,
		arg.TransactionID, arg.NetworkID, arg.TransactionHash, arg.VoutOrLogIdx,
		arg.Amount, arg.SenderAddress, arg.BlockNumber, arg.Confirmations, arg.Status, arg.ObservedAt,
	)
	var f TransactionFill
	err := row.Scan(
		&f.ID, &f.TransactionID, &f.NetworkID, &f.TransactionHash, &f.VoutOrLogIdx,
		&f.Amount, &f.SenderAddress, &f.BlockNumber, &f.Confirmations, &f.Status,
		&f.ObservedAt, &f.ConfirmedAt,
	)
	return f, err
}

const listTransactionFills = `
SELECT id, transaction_id, network_id, transaction_hash, vout_or_logidx,
       amount, sender_address, block_number, confirmations, status, observed_at, confirmed_at
FROM transaction_fills
WHERE transaction_id = $1
ORDER BY observed_at ASC
`

func (q *Queries) ListTransactionFills(ctx context.Context, transactionID int64) ([]TransactionFill, error) {
	rows, err := q.db.Query(ctx, listTransactionFills, transactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var items []TransactionFill
	for rows.Next() {
		var f TransactionFill
		if err := rows.Scan(
			&f.ID, &f.TransactionID, &f.NetworkID, &f.TransactionHash, &f.VoutOrLogIdx,
			&f.Amount, &f.SenderAddress, &f.BlockNumber, &f.Confirmations, &f.Status,
			&f.ObservedAt, &f.ConfirmedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, f)
	}
	return items, rows.Err()
}

// SumConfirmedFillsForTx returns the cumulative amount of fills that have
// reached confirmed status (per-chain confirmation threshold met). Fills in
// the "observed" or "reorged" state do NOT count toward the total — that
// safeguard prevents an unconfirmed/RBF'd top-up from prematurely flipping a
// payment to inProgress.
const sumConfirmedFillsForTx = `
SELECT COALESCE(SUM(amount), 0)::numeric
FROM transaction_fills
WHERE transaction_id = $1 AND status = 'confirmed'
`

func (q *Queries) SumConfirmedFillsForTx(ctx context.Context, transactionID int64) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, sumConfirmedFillsForTx, transactionID)
	var sum pgtype.Numeric
	err := row.Scan(&sum)
	return sum, err
}

// SumAllFillsForTx returns cumulative amount of all observed fills regardless
// of confirmation state. Used for the customer-facing "received so far"
// indicator on the payment page so that a recently-broadcast top-up shows up
// immediately even before its required confirmations land.
const sumAllFillsForTx = `
SELECT COALESCE(SUM(amount), 0)::numeric
FROM transaction_fills
WHERE transaction_id = $1 AND status <> 'reorged'
`

func (q *Queries) SumAllFillsForTx(ctx context.Context, transactionID int64) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, sumAllFillsForTx, transactionID)
	var sum pgtype.Numeric
	err := row.Scan(&sum)
	return sum, err
}

// FillExistsByHashAndRecipient is the watcher-side dedup guard. Returns true
// when the (network_id, transaction_hash, recipient_address) tuple has already
// been recorded as a fill against any pending/partial invoice. Recipient is
// joined from the parent transactions row, lower-cased on both sides because
// some chains store mixed-case (EIP-55 checksum) addresses.
const fillExistsByHashAndRecipient = `
SELECT EXISTS (
    SELECT 1
    FROM transaction_fills f
    JOIN transactions t ON t.id = f.transaction_id
    WHERE f.network_id = $1
      AND f.transaction_hash = $2
      AND lower(t.recipient_address) = lower($3)
)
`

func (q *Queries) FillExistsByHashAndRecipient(ctx context.Context, networkID, transactionHash, recipient string) (bool, error) {
	var exists bool
	err := q.db.QueryRow(ctx, fillExistsByHashAndRecipient, networkID, transactionHash, recipient).Scan(&exists)
	return exists, err
}
