// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package repository

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgtype"
)

const userColumns = `id, name, email, uuid, google_id, profile_image_url, created_at, updated_at, deleted_at, settings, password, is_super_admin, company_name, address, website, phone, email_verified, verification_token, verification_token_expires, marketing_consent, terms_accepted_at`

func scanUser(row interface{ Scan(...interface{}) error }, i *User) error {
	return row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Uuid,
		&i.GoogleID,
		&i.ProfileImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Settings,
		&i.Password,
		&i.IsSuperAdmin,
		&i.CompanyName,
		&i.Address,
		&i.Website,
		&i.Phone,
		&i.EmailVerified,
		&i.VerificationToken,
		&i.VerificationTokenExpires,
		&i.MarketingConsent,
		&i.TermsAcceptedAt,
	)
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    name, email, password, uuid, google_id, profile_image_url,
    is_super_admin, created_at, updated_at, deleted_at, settings,
    company_name, address, website, phone, email_verified,
    verification_token, verification_token_expires, marketing_consent, terms_accepted_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20)
RETURNING ` + userColumns

type CreateUserParams struct {
	Name                     string
	Email                    string
	Password                 sql.NullString
	Uuid                     uuid.UUID
	GoogleID                 sql.NullString
	ProfileImageUrl          sql.NullString
	IsSuperAdmin             sql.NullBool
	CreatedAt                time.Time
	UpdatedAt                time.Time
	DeletedAt                sql.NullTime
	Settings                 pgtype.JSONB
	CompanyName              sql.NullString
	Address                  sql.NullString
	Website                  sql.NullString
	Phone                    sql.NullString
	EmailVerified            sql.NullBool
	VerificationToken        sql.NullString
	VerificationTokenExpires sql.NullTime
	MarketingConsent         sql.NullBool
	TermsAcceptedAt          sql.NullTime
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Name,
		arg.Email,
		arg.Password,
		arg.Uuid,
		arg.GoogleID,
		arg.ProfileImageUrl,
		arg.IsSuperAdmin,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DeletedAt,
		arg.Settings,
		arg.CompanyName,
		arg.Address,
		arg.Website,
		arg.Phone,
		arg.EmailVerified,
		arg.VerificationToken,
		arg.VerificationTokenExpires,
		arg.MarketingConsent,
		arg.TermsAcceptedAt,
	)
	var i User
	err := scanUser(row, &i)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getSuperAdmins = `-- name: GetSuperAdmins :many
SELECT ` + userColumns + ` FROM users
WHERE is_super_admin = true
AND deleted_at is null
ORDER BY id ASC
`

func (q *Queries) GetSuperAdmins(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, getSuperAdmins)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := scanUser(rows, &i); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT ` + userColumns + ` FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := scanUser(row, &i)
	return i, err
}

const getUserByGoogleID = `-- name: GetUserByGoogleID :one
SELECT ` + userColumns + ` FROM users
WHERE google_id = $1 LIMIT 1
`

func (q *Queries) GetUserByGoogleID(ctx context.Context, googleID sql.NullString) (User, error) {
	row := q.db.QueryRow(ctx, getUserByGoogleID, googleID)
	var i User
	err := scanUser(row, &i)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT ` + userColumns + ` FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := scanUser(row, &i)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT ` + userColumns + ` FROM users
ORDER BY id desc
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := scanUser(rows, &i); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markUserAsSuperAdmin = `-- name: MarkUserAsSuperAdmin :exec
UPDATE users
SET is_super_admin = true, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkUserAsSuperAdmin(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markUserAsSuperAdmin, id)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET name = $2,
    profile_image_url= $3,
    google_id = CASE WHEN $6::boolean THEN $4 ELSE users.google_id END,
    updated_at = $5,
    company_name = CASE WHEN $7::text IS NOT NULL THEN $7 ELSE users.company_name END,
    address = CASE WHEN $8::text IS NOT NULL THEN $8 ELSE users.address END,
    website = CASE WHEN $9::text IS NOT NULL THEN $9 ELSE users.website END,
    phone = CASE WHEN $10::text IS NOT NULL THEN $10 ELSE users.phone END
WHERE id = $1
RETURNING ` + userColumns

type UpdateUserParams struct {
	ID              int64
	Name            string
	ProfileImageUrl sql.NullString
	GoogleID        sql.NullString
	UpdatedAt       time.Time
	SetGoogleID     bool
	CompanyName     sql.NullString
	Address         sql.NullString
	Website         sql.NullString
	Phone           sql.NullString
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Name,
		arg.ProfileImageUrl,
		arg.GoogleID,
		arg.UpdatedAt,
		arg.SetGoogleID,
		arg.CompanyName,
		arg.Address,
		arg.Website,
		arg.Phone,
	)
	var i User
	err := scanUser(row, &i)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :one
UPDATE users
SET password = $2,
    updated_at = $3
WHERE id = $1
RETURNING ` + userColumns

type UpdateUserPasswordParams struct {
	ID        int64
	Password  sql.NullString
	UpdatedAt time.Time
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserPassword, arg.ID, arg.Password, arg.UpdatedAt)
	var i User
	err := scanUser(row, &i)
	return i, err
}

// -- Email verification queries --

const setVerificationToken = `-- name: SetVerificationToken :exec
UPDATE users
SET verification_token = $2, verification_token_expires = $3, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) SetVerificationToken(ctx context.Context, id int64, token sql.NullString, expires sql.NullTime) error {
	_, err := q.db.Exec(ctx, setVerificationToken, id, token, expires)
	return err
}

const getUserByVerificationToken = `-- name: GetUserByVerificationToken :one
SELECT ` + userColumns + ` FROM users
WHERE verification_token = $1
AND verification_token_expires > NOW()
LIMIT 1
`

func (q *Queries) GetUserByVerificationToken(ctx context.Context, token string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByVerificationToken, token)
	var i User
	err := scanUser(row, &i)
	return i, err
}

const updateEmailVerified = `-- name: UpdateEmailVerified :exec
UPDATE users
SET email_verified = true, verification_token = NULL, verification_token_expires = NULL, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateEmailVerified(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, updateEmailVerified, id)
	return err
}
