// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: xpub_wallets.sql

package repository

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createXpubWallet = `-- name: CreateXpubWallet :one
INSERT INTO xpub_wallets (
    uuid, merchant_id, blockchain, xpub, derivation_path,
    created_at, updated_at, last_derived_index, is_active
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, uuid, merchant_id, blockchain, xpub, derivation_path, created_at, updated_at, tatum_subscription_id, last_derived_index, is_active
`

type CreateXpubWalletParams struct {
	Uuid             uuid.UUID
	MerchantID       int64
	Blockchain       string
	Xpub             string
	DerivationPath   string
	CreatedAt        time.Time
	UpdatedAt        time.Time
	LastDerivedIndex sql.NullInt32
	IsActive         sql.NullBool
}

func (q *Queries) CreateXpubWallet(ctx context.Context, arg CreateXpubWalletParams) (XpubWallet, error) {
	row := q.db.QueryRow(ctx, createXpubWallet,
		arg.Uuid,
		arg.MerchantID,
		arg.Blockchain,
		arg.Xpub,
		arg.DerivationPath,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.LastDerivedIndex,
		arg.IsActive,
	)
	var i XpubWallet
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.MerchantID,
		&i.Blockchain,
		&i.Xpub,
		&i.DerivationPath,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TatumSubscriptionID,
		&i.LastDerivedIndex,
		&i.IsActive,
	)
	return i, err
}

const deactivateXpubWallet = `-- name: DeactivateXpubWallet :exec
UPDATE xpub_wallets
SET is_active = false, updated_at = $2
WHERE id = $1
`

type DeactivateXpubWalletParams struct {
	ID        int64
	UpdatedAt time.Time
}

func (q *Queries) DeactivateXpubWallet(ctx context.Context, arg DeactivateXpubWalletParams) error {
	_, err := q.db.Exec(ctx, deactivateXpubWallet, arg.ID, arg.UpdatedAt)
	return err
}

const getXpubWalletByID = `-- name: GetXpubWalletByID :one
SELECT id, uuid, merchant_id, blockchain, xpub, derivation_path, created_at, updated_at, tatum_subscription_id, last_derived_index, is_active FROM xpub_wallets WHERE id = $1 LIMIT 1
`

func (q *Queries) GetXpubWalletByID(ctx context.Context, id int64) (XpubWallet, error) {
	row := q.db.QueryRow(ctx, getXpubWalletByID, id)
	var i XpubWallet
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.MerchantID,
		&i.Blockchain,
		&i.Xpub,
		&i.DerivationPath,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TatumSubscriptionID,
		&i.LastDerivedIndex,
		&i.IsActive,
	)
	return i, err
}

const getXpubWalletByMerchantAndBlockchain = `-- name: GetXpubWalletByMerchantAndBlockchain :one
SELECT id, uuid, merchant_id, blockchain, xpub, derivation_path, created_at, updated_at, tatum_subscription_id, last_derived_index, is_active FROM xpub_wallets
WHERE merchant_id = $1 AND blockchain = $2 AND is_active = true
LIMIT 1
`

type GetXpubWalletByMerchantAndBlockchainParams struct {
	MerchantID int64
	Blockchain string
}

func (q *Queries) GetXpubWalletByMerchantAndBlockchain(ctx context.Context, arg GetXpubWalletByMerchantAndBlockchainParams) (XpubWallet, error) {
	row := q.db.QueryRow(ctx, getXpubWalletByMerchantAndBlockchain, arg.MerchantID, arg.Blockchain)
	var i XpubWallet
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.MerchantID,
		&i.Blockchain,
		&i.Xpub,
		&i.DerivationPath,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TatumSubscriptionID,
		&i.LastDerivedIndex,
		&i.IsActive,
	)
	return i, err
}

const getXpubWalletByUUID = `-- name: GetXpubWalletByUUID :one
SELECT id, uuid, merchant_id, blockchain, xpub, derivation_path, created_at, updated_at, tatum_subscription_id, last_derived_index, is_active FROM xpub_wallets WHERE uuid = $1 LIMIT 1
`

func (q *Queries) GetXpubWalletByUUID(ctx context.Context, argUuid uuid.UUID) (XpubWallet, error) {
	row := q.db.QueryRow(ctx, getXpubWalletByUUID, argUuid)
	var i XpubWallet
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.MerchantID,
		&i.Blockchain,
		&i.Xpub,
		&i.DerivationPath,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TatumSubscriptionID,
		&i.LastDerivedIndex,
		&i.IsActive,
	)
	return i, err
}

const listXpubWalletsByMerchantID = `-- name: ListXpubWalletsByMerchantID :many
SELECT id, uuid, merchant_id, blockchain, xpub, derivation_path, created_at, updated_at, tatum_subscription_id, last_derived_index, is_active FROM xpub_wallets
WHERE merchant_id = $1 AND is_active = true
ORDER BY created_at DESC
`

func (q *Queries) ListXpubWalletsByMerchantID(ctx context.Context, merchantID int64) ([]XpubWallet, error) {
	rows, err := q.db.Query(ctx, listXpubWalletsByMerchantID, merchantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []XpubWallet
	for rows.Next() {
		var i XpubWallet
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.MerchantID,
			&i.Blockchain,
			&i.Xpub,
			&i.DerivationPath,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TatumSubscriptionID,
			&i.LastDerivedIndex,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateXpubWalletLastIndex = `-- name: UpdateXpubWalletLastIndex :one
UPDATE xpub_wallets
SET last_derived_index = $2, updated_at = $3
WHERE id = $1
RETURNING id, uuid, merchant_id, blockchain, xpub, derivation_path, created_at, updated_at, tatum_subscription_id, last_derived_index, is_active
`

type UpdateXpubWalletLastIndexParams struct {
	ID               int64
	LastDerivedIndex sql.NullInt32
	UpdatedAt        time.Time
}

func (q *Queries) UpdateXpubWalletLastIndex(ctx context.Context, arg UpdateXpubWalletLastIndexParams) (XpubWallet, error) {
	row := q.db.QueryRow(ctx, updateXpubWalletLastIndex, arg.ID, arg.LastDerivedIndex, arg.UpdatedAt)
	var i XpubWallet
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.MerchantID,
		&i.Blockchain,
		&i.Xpub,
		&i.DerivationPath,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TatumSubscriptionID,
		&i.LastDerivedIndex,
		&i.IsActive,
	)
	return i, err
}

const updateXpubWalletTatumSubscription = `-- name: UpdateXpubWalletTatumSubscription :one
UPDATE xpub_wallets
SET tatum_subscription_id = $2, updated_at = $3
WHERE id = $1
RETURNING id, uuid, merchant_id, blockchain, xpub, derivation_path, created_at, updated_at, tatum_subscription_id, last_derived_index, is_active
`

type UpdateXpubWalletTatumSubscriptionParams struct {
	ID                  int64
	TatumSubscriptionID sql.NullString
	UpdatedAt           time.Time
}

func (q *Queries) UpdateXpubWalletTatumSubscription(ctx context.Context, arg UpdateXpubWalletTatumSubscriptionParams) (XpubWallet, error) {
	row := q.db.QueryRow(ctx, updateXpubWalletTatumSubscription, arg.ID, arg.TatumSubscriptionID, arg.UpdatedAt)
	var i XpubWallet
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.MerchantID,
		&i.Blockchain,
		&i.Xpub,
		&i.DerivationPath,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TatumSubscriptionID,
		&i.LastDerivedIndex,
		&i.IsActive,
	)
	return i, err
}
