// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CreateMoneroTransactionRequest create monero transaction request
//
// swagger:model createMoneroTransactionRequest
type CreateMoneroTransactionRequest struct {

	// Wallet account index (for multi-account wallets)
	// Example: 0
	AccountIndex int64 `json:"accountIndex,omitempty"`

	// Raw amount in atomic units (piconeros)
	// Example: 100000000000
	// Required: true
	Amount string `json:"amount"`

	// Mainnet / Testnet selection
	// Required: true
	IsTestnet bool `json:"isTestnet"`

	// Transaction priority (0=default, 1=unimportant, 2=normal, 3=elevated, 4=priority)
	// Example: 0
	Priority int64 `json:"priority,omitempty"`

	// Recipient address
	// Example: 44AFFq5kSiGBoZ4NMDwYtN18obc8AemS33DBLWs3H7otXft3XjrpDtQGv7SqSsaBYBb98uNbr2VBBEt7f2wfn3RVGQBEP3A
	// Required: true
	Recipient string `json:"recipient"`
}

// Validate validates this create monero transaction request
func (m *CreateMoneroTransactionRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAmount(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRecipient(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CreateMoneroTransactionRequest) validateAmount(formats strfmt.Registry) error {

	if err := validate.RequiredString("amount", "body", m.Amount); err != nil {
		return err
	}

	return nil
}

func (m *CreateMoneroTransactionRequest) validateRecipient(formats strfmt.Registry) error {

	if err := validate.RequiredString("recipient", "body", m.Recipient); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this create monero transaction request based on context it is used
func (m *CreateMoneroTransactionRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreateMoneroTransactionRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateMoneroTransactionRequest) UnmarshalBinary(b []byte) error {
	var res CreateMoneroTransactionRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
