// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CreateSolanaTransactionRequest create solana transaction request
//
// swagger:model createSolanaTransactionRequest
type CreateSolanaTransactionRequest struct {

	// Raw amount in lamports or token decimals
	// Example: 1000000
	// Required: true
	Amount string `json:"amount"`

	// asset type
	// Required: true
	AssetType AssetType `json:"assetType"`

	// Mainnet / Devnet selection
	// Required: true
	IsTestnet bool `json:"isTestnet"`

	// Recipient address in base58
	// Example: 9B5XszUGdMaxCZ7uSQhPzdks5ZQSmWxrmzCSvtJ6Ns6g
	// Required: true
	Recipient string `json:"recipient"`

	// SPL token mint address (for token transfers)
	// Example: Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB
	TokenMint string `json:"tokenMint,omitempty"`
}

// Validate validates this create solana transaction request
func (m *CreateSolanaTransactionRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAmount(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateAssetType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRecipient(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CreateSolanaTransactionRequest) validateAmount(formats strfmt.Registry) error {

	if err := validate.RequiredString("amount", "body", m.Amount); err != nil {
		return err
	}

	return nil
}

func (m *CreateSolanaTransactionRequest) validateAssetType(formats strfmt.Registry) error {

	if err := validate.Required("assetType", "body", AssetType(m.AssetType)); err != nil {
		return err
	}

	if err := m.AssetType.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("assetType")
		}
		return err
	}

	return nil
}

func (m *CreateSolanaTransactionRequest) validateRecipient(formats strfmt.Registry) error {

	if err := validate.RequiredString("recipient", "body", m.Recipient); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this create solana transaction request based on the context it is used
func (m *CreateSolanaTransactionRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateAssetType(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CreateSolanaTransactionRequest) contextValidateAssetType(ctx context.Context, formats strfmt.Registry) error {

	if err := m.AssetType.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("assetType")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *CreateSolanaTransactionRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateSolanaTransactionRequest) UnmarshalBinary(b []byte) error {
	var res CreateSolanaTransactionRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
