// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// MoneroTransaction monero transaction
//
// swagger:model moneroTransaction
type MoneroTransaction struct {

	// Transaction fee in atomic units (piconeros)
	Amount string `json:"amount,omitempty"`

	// Transaction fee in atomic units (piconeros)
	Fee string `json:"fee,omitempty"`

	// Transaction hash
	TxHash string `json:"txHash,omitempty"`

	// Transaction key (for payment proof)
	TxKey string `json:"txKey,omitempty"`
}

// Validate validates this monero transaction
func (m *MoneroTransaction) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this monero transaction based on context it is used
func (m *MoneroTransaction) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MoneroTransaction) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MoneroTransaction) UnmarshalBinary(b []byte) error {
	var res MoneroTransaction
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
